Visible offline 2.0
OuterTune/OuterTune pull request #129
Opened 2024-12-11 18:08 UTC by mattcarter11

- centralize SongListItem logic
- select header also consider connection

2025-01-01 17:50 UTC, mikooomich commented on app/src/main/java/com/dd3boh/outertune/ui/screens/HistoryScreen.kt
> -        saver = listSaver<MutableList<Long>, Long>(
You can't just change this to String. The items (events) on the history screen need to be selectable individually (hence he long id of the event), whereas this refactor selects all of the same song.

2025-01-01 17:53 UTC, mikooomich requested changes
The above

2025-01-01 17:55 UTC, mikooomich commented on app/src/main/java/com/dd3boh/outertune/ui/screens/HistoryScreen.kt
> -        saver = listSaver<MutableList<Long>, Long>(
Same with duplicates in playlists (and any other places too?)

2025-01-03 15:47 UTC, mattcarter11 commented on app/src/main/java/com/dd3boh/outertune/ui/screens/HistoryScreen.kt
> -        saver = listSaver<MutableList<Long>, Long>(
Fixed, i've move the select logic outside the SongListItem, to each parent so they implement their own logic

2025-01-06 21:41 UTC, merged

2025-01-06 21:48 UTC, mikooomich commented
History screen multi select doesn't work for disable songs, but it does for playlist. Is this intentional?

2025-01-07 18:01 UTC, mattcarter11 commented
> History screen multi select doesn't work for disable songs, but it does for playlist. Is this intentional?

What do you mean exacly? Multiselect in history should be like any other place. If a song is available (curently have connection or is downloaded) should be selectable.

2025-01-07 22:52 UTC, mikooomich commented
I tested it again, and when offline it's not selectable across the board. I'm not sure if it's a issue after merging, however in it's current state, it's something like this

![Screenshot_20250107-174752_OuterTune Debug.png](https://github.com/user-attachments/assets/3d6873f9-0ccf-4d0a-83ee-7f625d010e74)

2025-01-08 06:56 UTC, mattcarter11 commented
It's not a bug, it's intentional, because the actions you can do with songs don't work when offline (like, add to library, playlist, download, play ...)

2025-01-08 19:24 UTC, mikooomich commented
Ah, ok. All good