strings: fix #168 + refactor
OuterTune/OuterTune pull request #173
Opened 2024-12-22 14:19 UTC by mattcarter11

Fix #168

2024-12-22 17:15 UTC, mikooomich commented
@mattcarter11 Hi. You seem to know your place around here pretty well... would you be interested in co-maintaining this app? Shoot me an email if you would like discuss a bit more! :)

2025-01-01 21:02 UTC, mikooomich requested changes

2025-01-01 21:02 UTC, mikooomich commented on app/src/main/java/com/dd3boh/outertune/ui/component/CreatePlaylistDialog.kt
> +            if (allowSyncing && context.isSyncEnabled()){
I think this prevents you from creating a synced playlist when auto sync is on. Auto sync toggle is automatic syncing, and  the user should be able to create and add to playlists (aka manual sync). Is this the behaviour you intended?

2025-01-03 14:34 UTC, mattcarter11 commented on app/src/main/java/com/dd3boh/outertune/ui/component/CreatePlaylistDialog.kt
> +            if (allowSyncing && context.isSyncEnabled()){
If I don't rememver wrong, the issue here was that it was possible to enable playlist sync while not being logged in, with this you can only have the option when you are logged. I've fixed to consider only this

2025-01-06 22:31 UTC, merged

2025-01-06 22:31 UTC, mikooomich commented
Thanks!