Singelton sync and chip loader
OuterTune/OuterTune pull request #63
Opened 2024-10-10 05:57 UTC by mattcarter11

- Include uploaded songs
- Make syncing of songs, albums, playlists, artist faster (corutines) and only allow one sync to run (singleton like)
- Show loading spinner in chip when syncing it
- Rename some functions

2024-10-15 20:55 UTC, mattcarter11 commented
@mikooomich this one has some big files 😅 if anything has to change, I'm more than happy to oblige

2024-10-16 01:08 UTC, mikooomich commented
As in a "this is ready for merge" or suggestions in general? I haven't looked into it too deeply, but looks great so far! A few things I noticed
- App crashes on database migration. You probably can just let auto migration handle it (you basically don't have to do anything for simple field additions), and onPostUpgrade() if necessary. The manual migrations are only really necessary for when auto migrations won't cut it
- On old layout (maybe new too?), switching tabs causes sync(?) even when auto sync is disabled

2024-10-16 16:30 UTC, mattcarter11 commented
@mikooomich db migration removed and fixed the ytmSync being ignored in the playlist tab

2024-10-16 18:12 UTC, mattcarter11 commented
@mikooomich also, what do you think about adding this? A n/m download count on playlists/artists/albums with any downloaded song

![Screenshot_2024-10-16-20-05-56-92_f7786a54783c2d596a4e4e9b85357647](https://github.com/user-attachments/assets/d8fe6738-2c82-4736-9244-e6d888510243)

2024-10-16 18:21 UTC, mikooomich commented
You cannot modify old db schema like that. You still need to increment db version and specify a database auto migration, see here -> https://github.com/DD3Boh/OuterTune/commit/c3e2ea7dc259209b10ab6666093a0a9f3f9c92c5#diff-841cb2099b74da4d913f1cf1d60c554d9e6ae0dc6f8c3a22ad3b95a4b5b39568R107

> A n/m download count on playlists/artists/albums with any downloaded song. Maybe add an option to toggle this?

Yeah, nice touch



If the pull request is wip could you mark it as such (with the selector), then mark it ready when its ready to be reviewed/merged

2024-10-17 21:30 UTC, mattcarter11 commented
@mikooomich change done and added N/M songs

2024-10-20 19:31 UTC, mikooomich requested changes
Hello. A few nitpicks, otherwise, looks great.

For commits, mostly for sakes of readability/traceability: 
- Please remove merge commit(s). PRs should be rebased on conflict, or left as-is 
- Remove any rebase fixup commits (those should be applied within commits themselves)
- Squash any duplicates ex. "fix sort lined song"
- All database schema should be contained within one commit. It's just the one change with SongEntity, right? All the json modifications, adding migration, etc can probably go into one commit
- Tagging.  You can leave this PR as is, however in the future, we'd very much prefer commits to be tagged according to functionality/category. ex "ui: ..." "syncutils: ...", etc. It just makes searching/skimming/grouping much easier 





Download icon is misaligned 
![image](https://github.com/user-attachments/assets/5b25c80d-481d-40cd-9702-452e48011a6f)


NPE crash when clicking on albums

```
 FATAL EXCEPTION: main
                                                                                                    Process: com.dd3boh.outertunepr63, PID: 4785
                                                                                                    java.lang.NullPointerException: Parameter specified as non-null is null: method androidx.room.RoomSQLiteQuery.bindString, parameter value
                                                                                                    	at androidx.room.RoomSQLiteQuery.bindString(Unknown Source:2)
                                                                                                    	at com.dd3boh.outertune.db.DatabaseDao_Impl.__fetchRelationshipartistAscomDd3bohOutertuneDbEntitiesArtistEntity_1(DatabaseDao_Impl.java:12905)
                                                                                                    	at com.dd3boh.outertune.db.DatabaseDao_Impl.-$$Nest$m__fetchRelationshipartistAscomDd3bohOutertuneDbEntitiesArtistEntity_1(Unknown Source:0)
                                                                                                    	at com.dd3boh.outertune.db.DatabaseDao_Impl$97.call(DatabaseDao_Impl.java:7750)
                                                                                                    	at com.dd3boh.outertune.db.DatabaseDao_Impl$97.call(DatabaseDao_Impl.java:7717)
                                                                                                    	at androidx.room.CoroutinesRoom$Companion$createFlow$1$1$1.invokeSuspend(CoroutinesRoom.kt:129)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)
                                                                                                    	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@b352779, Dispatchers.Main.immediate]
2024-10-20 13:01:55.637  4785-4785  Process                 com.dd3boh.outertunepr63             I  Sending signal. PID: 4785 SIG: 9
```

2024-10-20 19:31 UTC, mikooomich commented on app/schemas/com.dd3boh.outertune.db.InternalDatabase/15.json
This file should not be changed at all.  If you build DB 15 (before your DB16 changes), it should not modify this file from what is currently on dev branch

though, from the looks of it, you just forgot to revert this file's changes

2024-10-20 19:31 UTC, mikooomich commented on app/src/main/java/com/dd3boh/outertune/extensions/ContextExt.kt
> +        val cookie = dataStore.data.map { it[InnerTubeCookieKey] ?: "" }.first()
why not dataStore.get()

2024-10-20 19:31 UTC, mikooomich commented on app/src/main/java/com/dd3boh/outertune/db/MusicDatabase.kt
> +val MIGRATION_15_16 = object : Migration(15, 16) {
Auto migration does fail. Odd.

2024-10-20 19:31 UTC, mikooomich commented on app/src/main/java/com/dd3boh/outertune/db/daos/PlaylistsDao.kt
(Referring to all daos, not just playlist) Is there a pattern to what goes in the the specific daos vs the main dao?

For example `fun update(map: PlaylistSongMap)` is in the main dao, but `fun update(playlist: PlaylistEntity)` is in its own dao. Is this because the stuff that goes into the specific daos are entity specific? And then the main dao handles mapping and stuff?

But then shouldn't this be in the main dao?
```
   @Query("DELETE FROM playlist_song_map WHERE playlistId = :playlistId")
    fun clearPlaylist(playlistId: String)
```

Of course, this refactor is miles better than the monolithic DatabaseDao mess, but plz define what goes into where (maybe a comment block at the top of DatabaseDao.kt?), and be consistent

2024-10-21 20:51 UTC, mattcarter11 commented
@mikooomich 
- resolved all comments
- merge removed
- Squash some commits
- alignment fixed

- All database schema should be contained within one commit -> should i squash commits? what if they are mixed with other stuff?
- Remove any rebase fixup commits (those should be applied within commits themselves) -> what do you mean applied within commits themselves? the commits from the branch used to rebas (dev)?
- NPE crash when clicking on albums -> i didn't get any crash (i do get uploaded albums and artists page not loading), what triggered the crash?
- tags -> ok, I'll start using them from now on

2024-10-24 03:47 UTC, mikooomich commented
> All database schema should be contained within one commit -> should i squash commits? what if they are mixed with other stuff?

"migrate get download logic to SQL (+performance) and add isDownload to song table"
For this, i'd seperate the rest of the sql stuff (another commit) and add is downloaded (one commit) . When you add the isdownloaded field, it comes it side effects: you need to handle migration and room will generate the json for db V16. that should all be contained in that commit. 

This also means squash the following since into that commit since that will be handled in the commit you add isdownloaded
- remove db migration 
- add new versiondb file
- re-add migration since auto was failing
- revert 15.json changes 
- and any more i'm missing (?)

> Remove any rebase fixup commits (those should be applied within commits themselves) -> what do you mean applied within commits themselves? the commits from the branch used to rebas (dev)?

"add missing import after rebase" should not be its own commit (unless it's alot of fixing and makes sense to otherwise), instead, add it into the commit that needs it. (if you don't know where it came from, honestly you can just leave it as it)

2024-10-30 18:42 UTC, mattcarter11 commented
@mikooomich changes done

2024-11-01 16:00 UTC, merged